// Run with the local fixture servers described in gameplay-harness.md.
require('fs').mkdirSync('work/gameplay-audit', { recursive: true });
const assert = require('node:assert/strict');
const { chromium, webkit } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
    for (const name of ['chromium', 'webkit']) {
        const browser = await (name === 'webkit' ? webkit : chromium).launch({ headless: true, ...(name === 'chromium' && process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? { executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE } : {}) });
        for (const width of [390, 820, 1440]) {
            const page = await browser.newPage({ viewport: { width, height: 1100 }, hasTouch: true });
            const errors = [];
            page.on('pageerror', e => errors.push(e.message));
            const tap = async (s) => page.locator(`[data-square="${s}"]`).tap();
            await page.goto('http://127.0.0.1:9417');
            await tap('g1');
            await page.getByRole('button', { name: 'Opponent e5', exact: true }).click();
            await tap('f3');
            await page.waitForFunction(() => window.boardTest.moves.length === 1);
            assert.equal((await page.evaluate(() => window.boardTest.moves[0])).to, 'f3');
            await page.getByRole('button', { name: 'Reset', exact: true }).click();
            await tap('g1');
            await tap('g1');
            assert.equal(await page.evaluate(() => window.boardTest.moves.length), 0);
            await page.getByRole('button', { name: 'Opponent e5', exact: true }).click();
            const key = page.locator('[data-board-square="g1"]');
            await key.focus();
            await page.keyboard.press('Enter');
            await page.keyboard.press('ArrowUp');
            await page.waitForFunction(() => document.activeElement.dataset.boardSquare === 'g2');
            await page.keyboard.press('ArrowUp');
            await page.waitForFunction(() => document.activeElement.dataset.boardSquare === 'g3');
            await page.keyboard.press('ArrowLeft');
            await page.waitForFunction(() => document.activeElement.dataset.boardSquare === 'f3');
            await page.keyboard.press('Enter');
            await page.waitForFunction(() => window.boardTest.moves.length === 1);
            await page.getByRole('button', { name: 'Lock board', exact: true }).click();
            await tap('d2');
            await tap('d4');
            assert.equal(await page.evaluate(() => window.boardTest.moves.length), 1);
            await page.getByRole('button', { name: 'Reset', exact: true }).click();
            await page.getByRole('button', { name: 'Reply during next drag', exact: true }).click();
            const a = await page.locator('[data-square="g1"]').boundingBox(), z = await page.locator('[data-square="f3"]').boundingBox();
            await page.mouse.move(a.x + a.width / 2, a.y + a.height / 2);
            await page.mouse.down();
            await page.mouse.move(a.x + a.width / 2 + 12, a.y + a.height / 2 - 12, { steps: 3 });
            await page.waitForFunction(() => window.boardTest.fen.includes('4p3'));
            await page.mouse.move(z.x + z.width / 2, z.y + z.height / 2, { steps: 8 });
            await page.waitForTimeout(150);
            await page.mouse.up();
            await page.waitForFunction(() => window.boardTest.moves.length === 1);
            await page.goto('http://127.0.0.1:9417/?live');
            await tap('e2');
            await tap('e4');
            await tap('g1');
            await tap('f3');
            await page.waitForFunction(() => window.liveTest.requests.length === 1);
            assert.equal(await page.evaluate(() => window.liveTest.requests[0].from), 'e2');
            await page.getByRole('button', { name: 'Confirm pending move', exact: true }).click();
            await page.getByRole('button', { name: 'Opponent e5', exact: true }).click();
            await page.waitForFunction(() => window.liveTest.requests.length === 2);
            assert.equal(await page.evaluate(() => window.liveTest.requests[1].from), 'g1');
            await page.getByRole('button', { name: 'Confirm pending move', exact: true }).click();
            await page.getByRole('button', { name: 'Deliver stale snapshot', exact: true }).click();
            await page.waitForFunction(() => document.querySelector('[data-square="f3"] [data-piece]'));
            assert.equal(await page.evaluate(() => window.liveTest.requests.length), 2);
            await page.screenshot({ path: `work/gameplay-audit/${name}-live-${width}.png`, fullPage: true });
            await page.goto('http://127.0.0.1:9417/?live');
            await tap('e2');
            await tap('e4');
            await tap('g1');
            await tap('f3');
            await page.getByRole('button', { name: 'Reject pending move', exact: true }).click();
            await page.waitForFunction(() => document.querySelector('[data-square="e2"] [data-piece]'));
            assert.equal(await page.evaluate(() => window.liveTest.requests.length), 1);
            assert.deepEqual(errors, []);
            console.log(`${name} ${width}: tap, deselect, keyboard, locked board, drag during reply, premove, stale snapshot and rollback passed`);
            await page.close();
        }
        await browser.close();
    }
})().catch(e => { console.error(e); process.exit(1); });
