import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { buildSirLemProfile, type LichessProfileGame } from "./lib/buildSirLemProfile";

async function main() {
  // Offline replay makes a public export reproducible without extra API traffic.
  const fromIndex = process.argv.indexOf("--from");
  if (fromIndex >= 0 && !process.argv[fromIndex + 1]) throw new Error("--from requires a public NDJSON export path.");
  let payload: string;
  if (fromIndex >= 0) {
    payload = await readFile(resolve(process.argv[fromIndex + 1]), "utf8");
  } else {
    const query = new URLSearchParams({ max: "5000", rated: "true", perfType: "bullet,blitz,rapid,classical,correspondence",
      moves: "true", clocks: "false", evals: "false", opening: "false", pgnInJson: "false" });
    const response = await fetch(`https://lichess.org/api/games/user/so_pawny?${query}`, {
      headers: { Accept: "application/x-ndjson", "User-Agent": "TheChessAcademyBotProfile/2.0" },
      signal: AbortSignal.timeout(600_000)
    });
    // Never replace the known-good profile after an API error or rate limit.
    if (!response.ok) throw new Error(`Lichess game export failed (${response.status}). Existing profile retained.`);
    payload = await response.text();
  }
  const games = payload.split(/\r?\n/).filter(Boolean).map((line) => JSON.parse(line) as LichessProfileGame);
  const { repertoire, source } = buildSirLemProfile(games);
  if (source.games < 3_000 || source.positions < 600) throw new Error("Incomplete public export. Existing profile retained.");
  const header = "// Generated by npm run update:sir-lem-bot from public rated standard Lichess games.\n";
  const book = `${header}import type { BotRepertoire } from "@/chess/types";\n\nexport const SIR_LEM_REPERTOIRE: BotRepertoire = {\n${Object.entries(repertoire).map(([key, moves]) => `  ${JSON.stringify(key)}: ${JSON.stringify(moves)},`).join("\n")}\n};\n`;
  await writeFile(resolve("chess/bots/sirLemRepertoire.ts"), book, "utf8");
  await writeFile(resolve("chess/bots/sirLemProfile.ts"), `${header}export const SIR_LEM_SOURCE = ${JSON.stringify(source, null, 2)} as const;\n`, "utf8");
  process.stdout.write(`${JSON.stringify(source, null, 2)}\n`);
}

void main().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
});
