import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { Chess } from "chess.js";
import type { BotOpeningRule } from "../chess/types";

const LICHESS_USERNAME = "So_Pawny";
const LICHESS_USER_ID = "so_pawny";
const MAX_GAMES = 5_000;
const MAX_OPENING_PLY = 24;
const MIN_POSITION_SAMPLES = 3;
const MAX_RULES = 600;
const MAX_CHOICES_PER_POSITION = 4;
const OUTPUT_PATH = resolve(process.cwd(), "chess/bots/sirLemOpeningBook.ts");

type LichessPlayer = { user?: { id?: string; name?: string } };
type LichessGame = {
  id?: string;
  variant?: string;
  rated?: boolean;
  createdAt?: number;
  moves?: string;
  players?: { white?: LichessPlayer; black?: LichessPlayer };
};

type PositionStats = {
  after: string[];
  total: number;
  moves: Map<string, number>;
};

function parseNdjson(payload: string) {
  return payload
    .split(/\r?\n/)
    .filter(Boolean)
    .map((line) => JSON.parse(line) as LichessGame);
}

function playerColor(game: LichessGame) {
  if (game.players?.white?.user?.id?.toLowerCase() === LICHESS_USER_ID) return "white" as const;
  if (game.players?.black?.user?.id?.toLowerCase() === LICHESS_USER_ID) return "black" as const;
  return null;
}

function gameUciMoves(game: LichessGame) {
  const chess = new Chess();
  const moves: string[] = [];
  for (const san of game.moves?.trim().split(/\s+/).filter(Boolean) ?? []) {
    const move = chess.move(san);
    moves.push(`${move.from}${move.to}${move.promotion ?? ""}`);
  }
  return moves;
}

function openingBonus(count: number, total: number) {
  return Math.round(45 + 105 * Math.sqrt(count / total));
}

function buildOpeningBook(games: LichessGame[]) {
  const positions = new Map<string, PositionStats>();
  let validGames = 0;
  let latestGameAt = 0;

  for (const game of games) {
    if (!game.rated || game.variant !== "standard") continue;
    const color = playerColor(game);
    if (!color) continue;

    let moves: string[];
    try {
      moves = gameUciMoves(game);
    } catch {
      continue;
    }
    if (!moves.length) continue;

    validGames += 1;
    latestGameAt = Math.max(latestGameAt, game.createdAt ?? 0);
    for (let index = color === "white" ? 0 : 1; index < moves.length && index < MAX_OPENING_PLY; index += 2) {
      const after = moves.slice(0, index);
      const key = after.join(" ");
      const stats = positions.get(key) ?? { after, total: 0, moves: new Map<string, number>() };
      const move = moves[index];
      stats.total += 1;
      stats.moves.set(move, (stats.moves.get(move) ?? 0) + 1);
      positions.set(key, stats);
    }
  }

  const supported = [...positions.values()]
    .filter((position) => position.total >= MIN_POSITION_SAMPLES)
    .sort((left, right) => right.total - left.total || left.after.length - right.after.length || left.after.join(" ").localeCompare(right.after.join(" ")))
    .slice(0, MAX_RULES);

  const book: BotOpeningRule[] = supported.map((position) => {
    const rankedMoves = [...position.moves.entries()]
      .sort((left, right) => right[1] - left[1] || left[0].localeCompare(right[0]));
    const choices = rankedMoves
      .filter(([, count], index) => index === 0 || count >= 2)
      .slice(0, MAX_CHOICES_PER_POSITION);
    return {
      after: position.after,
      moves: choices.map(([uci, count]) => ({ uci, bonus: openingBonus(count, position.total) }))
    };
  }).sort((left, right) => left.after.length - right.after.length || left.after.join(" ").localeCompare(right.after.join(" ")));

  return { book, validGames, latestGameAt };
}

function generatedModule(book: BotOpeningRule[], validGames: number, latestGameAt: number) {
  const rules = book.map((rule) => `  ${JSON.stringify(rule)},`).join("\n");
  return `import type { BotOpeningRule } from "@/chess/types";

// Generated by npm run update:sir-lem-bot from public rated standard Lichess games.
export const SIR_LEM_SOURCE = {
  username: ${JSON.stringify(LICHESS_USERNAME)},
  games: ${validGames},
  openingPositions: ${book.length},
  maxOpeningPly: ${MAX_OPENING_PLY},
  updatedThrough: ${JSON.stringify(latestGameAt ? new Date(latestGameAt).toISOString() : null)}
} as const;

export const SIR_LEM_OPENING_BOOK: BotOpeningRule[] = [
${rules}
];
`;
}

async function main() {
  const query = new URLSearchParams({
    max: String(MAX_GAMES),
    rated: "true",
    perfType: "bullet,blitz,rapid,classical,correspondence",
    moves: "true",
    clocks: "false",
    evals: "false",
    opening: "false",
    pgnInJson: "true"
  });
  const response = await fetch(`https://lichess.org/api/games/user/${encodeURIComponent(LICHESS_USERNAME)}?${query}`, {
    headers: {
      Accept: "application/x-ndjson",
      "User-Agent": "TheChessAcademyBotProfile/1.0"
    }
  });
  if (!response.ok) throw new Error(`Lichess game export failed (${response.status} ${response.statusText}).`);

  const games = parseNdjson(await response.text());
  const { book, validGames, latestGameAt } = buildOpeningBook(games);
  if (validGames < 300) throw new Error(`Only ${validGames} valid games were returned; refusing to replace the existing 300-game profile.`);
  if (!book.length) throw new Error("No supported opening positions were generated.");

  await writeFile(OUTPUT_PATH, generatedModule(book, validGames, latestGameAt), "utf8");
  process.stdout.write(`Updated Sir Lem from ${validGames} rated standard games with ${book.length} opening positions through ${new Date(latestGameAt).toISOString()}.\n`);
}

void main().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
});
