// Generated by npm run update:sir-lem-bot from public rated standard Lichess games.
export const SIR_LEM_SOURCE = {
  "username": "So_Pawny",
  "games": 3238,
  "positions": 1678,
  "observedMoves": 86676,
  "rememberedMoves": 12233,
  "updatedThrough": "2026-09-03T07:55:16.051Z",
  "version": 2,
  "maxPly": 80,
  "minPositionGames": 2,
  "maxPositions": 6000,
  "recencyHalfLifeDays": 180
} as const;
