-- Release step 3: apply only after the schema migration and compatible app
-- deployment. Keeping activation separate prevents older app code from
-- misreading this new condition as an ordinary solved-puzzle quest.

insert into public.academy_quests (
  id,
  title,
  description,
  type,
  status,
  is_live,
  xp_reward,
  badge_reward_id,
  completion_url,
  class_group,
  category,
  source,
  condition_type,
  time_window,
  required_count,
  required_score,
  required_accuracy,
  required_theme,
  required_opponent_id,
  approval_required,
  is_active,
  is_repeatable,
  cooldown_days
)
values (
  'academy-conquer-woodpecker',
  'Conquer the Woodpecker',
  'Complete all three cycles of one 20-puzzle Woodpecker Method set.',
  'weekly',
  'available',
  true,
  200,
  null,
  '/student/training',
  null,
  'Academy',
  'internal_puzzles',
  'internal_woodpecker_set_completed_count',
  'weekly',
  1,
  null,
  null,
  null,
  null,
  false,
  true,
  true,
  7
)
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  type = excluded.type,
  status = excluded.status,
  is_live = excluded.is_live,
  xp_reward = excluded.xp_reward,
  badge_reward_id = excluded.badge_reward_id,
  completion_url = excluded.completion_url,
  class_group = excluded.class_group,
  category = excluded.category,
  source = excluded.source,
  condition_type = excluded.condition_type,
  time_window = excluded.time_window,
  required_count = excluded.required_count,
  required_score = excluded.required_score,
  required_accuracy = excluded.required_accuracy,
  required_theme = excluded.required_theme,
  required_opponent_id = excluded.required_opponent_id,
  approval_required = excluded.approval_required,
  is_active = excluded.is_active,
  is_repeatable = excluded.is_repeatable,
  cooldown_days = excluded.cooldown_days,
  updated_at = now();
