-- Additive rollout. Apply on release; old games are deliberately not enqueued.
create table public.game_achievement_release (
  singleton boolean primary key default true check(singleton),
  launched_at timestamptz not null default now()
);
insert into public.game_achievement_release(singleton) values(true);
alter table public.game_achievement_release enable row level security;
revoke all on public.game_achievement_release from anon, authenticated;
grant select on public.game_achievement_release to service_role;

create table public.game_achievement_rules (
  key text primary key,
  badge_id uuid not null unique references public.badges(id) on delete cascade
);
alter table public.game_achievement_rules enable row level security;
revoke all on public.game_achievement_rules from anon, authenticated;
grant select on public.game_achievement_rules to service_role;

alter table public.student_badges add column achievement_evidence jsonb;
create table public.game_achievement_scans (
  student_id uuid not null references public.students(id) on delete cascade,
  source_id text not null,
  internal_game_id uuid references public.internal_chess_games(id) on delete cascade,
  started_at timestamptz not null,
  completed_at timestamptz not null,
  opponent_key text not null,
  won boolean not null,
  payload jsonb,
  processed_at timestamptz,
  validation_error text,
  primary key(student_id,source_id)
);
create index game_achievement_scans_pending on public.game_achievement_scans(student_id,completed_at,source_id) where processed_at is null;
create index game_achievement_scans_streak on public.game_achievement_scans(student_id,completed_at desc,source_id desc);
create index game_achievement_scans_internal on public.game_achievement_scans(internal_game_id) where internal_game_id is not null;
alter table public.game_achievement_scans enable row level security;
revoke all on public.game_achievement_scans from anon,authenticated;
grant select,insert,update on public.game_achievement_scans to service_role;

create function public.enqueue_game_achievements() returns trigger
language plpgsql security invoker set search_path='' as $$
begin
  if new.started_at >= (select launched_at from public.game_achievement_release where singleton)
     and new.initial_fen='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'
     and coalesce(new.takeback_count,0)=0 and jsonb_array_length(new.moves)>0 then
    insert into public.game_achievement_scans(student_id,source_id,internal_game_id,started_at,completed_at,opponent_key,won)
    values(new.player_id,'academy:'||new.id,new.id,new.started_at,new.completed_at,
      'academy:'||new.opponent_type||':'||new.opponent_id,new.result='win')
    on conflict do nothing;
  end if;
  return new;
end $$;
revoke all on function public.enqueue_game_achievements() from public,anon,authenticated;
grant execute on function public.enqueue_game_achievements() to service_role;
create trigger enqueue_game_achievements after insert on public.internal_chess_games
for each row execute function public.enqueue_game_achievements();

-- Completion, badge, XP, coins (existing XP trigger), and evidence are one transaction.
-- Only trusted server code may submit detections; no browser RPC access.
create function public.complete_game_achievement_scan(p_student_id uuid,p_source_id text,p_hits jsonb)
returns integer language plpgsql security invoker set search_path='' as $$
declare scan public.game_achievement_scans%rowtype; hit jsonb; rule record;
  awarded uuid; award_count integer:=0; streak integer:=0; previous record;
begin
  perform pg_advisory_xact_lock(hashtextextended('game-achievements:'||p_student_id,0));
  select * into scan from public.game_achievement_scans where student_id=p_student_id and source_id=p_source_id for update;
  if not found or scan.processed_at is not null then return 0; end if;
  if scan.started_at < (select launched_at from public.game_achievement_release where singleton) then
    update public.game_achievement_scans set processed_at=now(),payload=null where student_id=p_student_id and source_id=p_source_id;
    return 0;
  end if;
  if p_hits is null or jsonb_typeof(p_hits)<>'array' or jsonb_array_length(p_hits)>80 then raise exception 'Invalid achievement evidence'; end if;
  -- Academy history is complete. A capped Lichess import cannot prove a streak.
  if scan.won and scan.internal_game_id is not null then
    for previous in select won,opponent_key from public.game_achievement_scans
      where student_id=p_student_id and internal_game_id is not null and (completed_at,source_id)<=(scan.completed_at,scan.source_id)
      order by completed_at desc,source_id desc limit 20
    loop
      exit when not previous.won or previous.opponent_key<>scan.opponent_key;
      streak:=streak+1;
    end loop;
    if streak>=10 then p_hits:=p_hits||jsonb_build_array(jsonb_build_object('key','adoption','ply',0)); end if;
    if streak>=20 then p_hits:=p_hits||jsonb_build_array(jsonb_build_object('key','double-adoption','ply',0)); end if;
  end if;
  for hit in select value from jsonb_array_elements(p_hits) loop
    select b.id,b.name,b.xp_value into rule from public.game_achievement_rules r join public.badges b on b.id=r.badge_id where r.key=hit->>'key';
    if not found then raise exception 'Unknown achievement'; end if;
    awarded:=null;
    insert into public.student_badges(student_id,badge_id,note,achievement_evidence)
    values(p_student_id,rule.id,'Automatically earned in a completed game.',
      jsonb_build_object('sourceId',scan.source_id,'ply',coalesce((hit->>'ply')::integer,0),'fen',hit->>'fen','completedAt',scan.completed_at))
    on conflict(student_id,badge_id) do nothing returning id into awarded;
    if awarded is not null then
      update public.students set total_xp=coalesce(total_xp,0)+rule.xp_value where id=p_student_id;
      insert into public.xp_events(student_id,amount,reason) values(p_student_id,rule.xp_value,'Game achievement: '||rule.name);
      insert into public.activity_events(student_id,event_type,title,description)
      values(p_student_id,'badge_earned',rule.name,'Earned '||rule.xp_value||' XP and '||rule.xp_value||' Academy Coins.');
      award_count:=award_count+1;
    end if;
  end loop;
  update public.game_achievement_scans set processed_at=now(),payload=null where student_id=p_student_id and source_id=p_source_id;
  return award_count;
end $$;
revoke all on function public.complete_game_achievement_scan(uuid,text,jsonb) from public,anon,authenticated;
grant execute on function public.complete_game_achievement_scan(uuid,text,jsonb) to service_role;
-- BEGIN GENERATED CATALOG
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000001','Fork Finder','Game achievement · Learning','Creativity','C','25','Create a fork, then capture one of its targets with the forking piece on your next turn without immediately losing that piece.','Chess Quest game achievement','/badges/game-achievements/first-fork.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('first-fork','ce550000-0000-4000-8000-000000000001') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000002','Pin and Win','Game achievement · Learning','Creativity','C','25','Pin a piece to its king, then capture that pinned piece on your next turn without an immediate recapture.','Chess Quest game achievement','/badges/game-achievements/successful-pin.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('successful-pin','ce550000-0000-4000-8000-000000000002') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000003','Skewer Scout','Game achievement · Learning','Creativity','C','25','Check with a bishop, rook or queen aligned with another enemy piece, then capture the piece behind the king on your next turn.','Chess Quest game achievement','/badges/game-achievements/first-skewer.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('first-skewer','ce550000-0000-4000-8000-000000000003') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000004','Hidden Helper','Game achievement · Learning','Creativity','C','25','Move a blocker to reveal a bishop, rook or queen attack, then use that revealed piece to capture the target on your next turn.','Chess Quest game achievement','/badges/game-achievements/discovered-attack.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('discovered-attack','ce550000-0000-4000-8000-000000000004') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000005','Back-Rank Hero','Game achievement · Learning','Creativity','C','25','Deliver rook or queen checkmate along the enemy back rank, with its king trapped by its own pieces on the rank in front.','Chess Quest game achievement','/badges/game-achievements/back-rank-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('back-rank-mate','ce550000-0000-4000-8000-000000000005') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000006','Pawn''s Journey','Game achievement · Learning','Creativity','C','25','Promote a pawn in a completed game.','Chess Quest game achievement','/badges/game-achievements/first-promotion.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('first-promotion','ce550000-0000-4000-8000-000000000006') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000007','Great Escape','Game achievement · Learning','Creativity','C','25','Be the stalemated player while behind in material by at least a pawn. Stalemate is a draw, not a win.','Chess Quest game achievement','/badges/game-achievements/stalemate-escape.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('stalemate-escape','ce550000-0000-4000-8000-000000000007') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000008','Watchful Eye','Game achievement · Learning','Creativity','C','25','Capture an undefended knight, bishop, rook or queen, and keep the capturing piece through the opponent''s next move.','Chess Quest game achievement','/badges/game-achievements/hanging-piece.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('hanging-piece','ce550000-0000-4000-8000-000000000008') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000009','Oh No My Queen','Game achievement · Surprises','Creativity','B','50','After your queen is captured, checkmate within your next three moves while the opponent still has a queen. No promoted queens in the game.','Chess Quest game achievement','/badges/game-achievements/oh-no-my-queen.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('oh-no-my-queen','ce550000-0000-4000-8000-000000000009') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000010','Stalemate Tricks','Game achievement · Surprises','Creativity','B','50','Escape with stalemate while at least four points behind, or at least two points behind outside a bishop-and-pawn-only ending.','Chess Quest game achievement','/badges/game-achievements/stalemate-tricks.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('stalemate-tricks','ce550000-0000-4000-8000-000000000010') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000011','Rosen Trap','Game achievement · Surprises','Creativity','A','100','Decline a legal king capture of a checking queen, move your king to a corner, then be stalemated on the next move.','Chess Quest game achievement','/badges/game-achievements/rosen-trap.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('rosen-trap','ce550000-0000-4000-8000-000000000011') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000012','Castle Fork','Game achievement · Surprises','Creativity','B','50','Castle with check, then capture an enemy piece with your king on your next turn.','Chess Quest game achievement','/badges/game-achievements/castle-fork.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('castle-fork','ce550000-0000-4000-8000-000000000012') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000013','Connect 5','Game achievement · Structures','Creativity','B','50','Form an unbroken diagonal of five of your pawns.','Chess Quest game achievement','/badges/game-achievements/connect-5.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('connect-5','ce550000-0000-4000-8000-000000000013') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000014','Pawn Diamond','Game achievement · Structures','Creativity','B','50','Arrange four of your pawns as a diamond: top, left, right and bottom.','Chess Quest game achievement','/badges/game-achievements/pawn-diamond.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('pawn-diamond','ce550000-0000-4000-8000-000000000014') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000015','Connect 6','Game achievement · Structures','Creativity','A','100','Form an unbroken diagonal of six of your pawns.','Chess Quest game achievement','/badges/game-achievements/connect-6.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('connect-6','ce550000-0000-4000-8000-000000000015') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000016','Double Pawn Diamond','Game achievement · Structures','Creativity','A','100','Have at least two pawn diamonds at once; they may share pawns.','Chess Quest game achievement','/badges/game-achievements/double-pawn-diamond.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('double-pawn-diamond','ce550000-0000-4000-8000-000000000016') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000017','Pawn X','Game achievement · Structures','Creativity','B','50','Arrange five of your pawns in a 3-by-3 X shape.','Chess Quest game achievement','/badges/game-achievements/pawn-x.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('pawn-x','ce550000-0000-4000-8000-000000000017') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000018','Solid Pawn Diamond','Game achievement · Structures','Creativity','B','50','Make a pawn diamond with a fifth pawn in its center.','Chess Quest game achievement','/badges/game-achievements/solid-pawn-diamond.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('solid-pawn-diamond','ce550000-0000-4000-8000-000000000018') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000019','Pawn Cube','Game achievement · Structures','Creativity','B','50','Arrange four of your pawns in a 2-by-2 square.','Chess Quest game achievement','/badges/game-achievements/pawn-cube.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('pawn-cube','ce550000-0000-4000-8000-000000000019') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000020','Center Pawn Cube','Game achievement · Structures','Creativity','B','50','Occupy d4, e4, d5 and e5 with your pawns.','Chess Quest game achievement','/badges/game-achievements/center-pawn-cube.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('center-pawn-cube','ce550000-0000-4000-8000-000000000020') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000021','Quadrupled Pawns','Game achievement · Structures','Creativity','B','50','Have four of your pawns on one file.','Chess Quest game achievement','/badges/game-achievements/quadrupled-pawns.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('quadrupled-pawns','ce550000-0000-4000-8000-000000000021') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000022','Connect 8 on 4th Rank','Game achievement · Structures','Creativity','A','100','Place all eight pawns on your fourth rank (rank 5 for Black).','Chess Quest game achievement','/badges/game-achievements/connect-8-rank-4.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('connect-8-rank-4','ce550000-0000-4000-8000-000000000022') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000023','Connect 8 on 5th Rank','Game achievement · Structures','Creativity','A','100','Place all eight pawns on your fifth rank (rank 4 for Black).','Chess Quest game achievement','/badges/game-achievements/connect-8-rank-5.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('connect-8-rank-5','ce550000-0000-4000-8000-000000000023') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000024','Connect 8 on 6th Rank','Game achievement · Structures','Creativity','A','100','Place all eight pawns on your sixth rank (rank 3 for Black).','Chess Quest game achievement','/badges/game-achievements/connect-8-rank-6.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('connect-8-rank-6','ce550000-0000-4000-8000-000000000024') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000025','Connect 8 on 7th Rank','Game achievement · Structures','Creativity','A','100','Place all eight pawns on your seventh rank (rank 2 for Black).','Chess Quest game achievement','/badges/game-achievements/connect-8-rank-7.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('connect-8-rank-7','ce550000-0000-4000-8000-000000000025') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000026','6 Pawns on the Same File','Game achievement · Structures','Creativity','A','100','Reach a position with six pawns on one file; both colors may contribute.','Chess Quest game achievement','/badges/game-achievements/six-pawns-file.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('six-pawns-file','ce550000-0000-4000-8000-000000000026') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000027','Knight Cube','Game achievement · Structures','Creativity','A','100','Arrange four of your knights in a 2-by-2 square.','Chess Quest game achievement','/badges/game-achievements/knight-cube.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('knight-cube','ce550000-0000-4000-8000-000000000027') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000028','Knight Rectangle','Game achievement · Structures','Creativity','A','100','Arrange six of your knights in a 2-by-3 or 3-by-2 rectangle.','Chess Quest game achievement','/badges/game-achievements/knight-rectangle.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('knight-rectangle','ce550000-0000-4000-8000-000000000028') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000029','Egg','Game achievement · Opening Curiosities','Creativity','B','50','Win after your opening moves spell “egg” using the first letter of each move in standard chess notation (uppercase B means bishop).','Chess Quest game achievement','/badges/game-achievements/alphabet-egg.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('alphabet-egg','ce550000-0000-4000-8000-000000000029') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000030','Double Egg (EggEgg)','Game achievement · Opening Curiosities','Creativity','B','50','Win after your opening moves spell “eggegg” using the first letter of each move in standard chess notation (uppercase B means bishop).','Chess Quest game achievement','/badges/game-achievements/alphabet-eggegg.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('alphabet-eggegg','ce550000-0000-4000-8000-000000000030') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000031','Bad Egg','Game achievement · Opening Curiosities','Creativity','B','50','Win after your opening moves spell “badegg” using the first letter of each move in standard chess notation (uppercase B means bishop).','Chess Quest game achievement','/badges/game-achievements/alphabet-badegg.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('alphabet-badegg','ce550000-0000-4000-8000-000000000031') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000032','BeachCafé','Game achievement · Opening Curiosities','Creativity','B','50','Win after your opening moves spell “beachcafe” using the first letter of each move in standard chess notation (uppercase B means bishop).','Chess Quest game achievement','/badges/game-achievements/alphabet-beachcafe.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('alphabet-beachcafe','ce550000-0000-4000-8000-000000000032') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000033','Beef','Game achievement · Opening Curiosities','Creativity','B','50','Win after your opening moves spell “beef” using the first letter of each move in standard chess notation (uppercase B means bishop).','Chess Quest game achievement','/badges/game-achievements/alphabet-beef.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('alphabet-beef','ce550000-0000-4000-8000-000000000033') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000034','Cabbage','Game achievement · Opening Curiosities','Creativity','B','50','Win after your opening moves spell “cabbage” using the first letter of each move in standard chess notation (uppercase B means bishop).','Chess Quest game achievement','/badges/game-achievements/alphabet-cabbage.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('alphabet-cabbage','ce550000-0000-4000-8000-000000000034') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000035','Chad','Game achievement · Opening Curiosities','Creativity','B','50','Win after your opening moves spell “chad” using the first letter of each move in standard chess notation (uppercase B means bishop).','Chess Quest game achievement','/badges/game-achievements/alphabet-chad.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('alphabet-chad','ce550000-0000-4000-8000-000000000035') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000036','Headache','Game achievement · Opening Curiosities','Creativity','B','50','Win after your opening moves spell “headache” using the first letter of each move in standard chess notation (uppercase B means bishop).','Chess Quest game achievement','/badges/game-achievements/alphabet-headache.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('alphabet-headache','ce550000-0000-4000-8000-000000000036') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000037','Checkmate with a Pawn','Game achievement · Checkmates','Creativity','B','50','Make a non-promotion pawn move that delivers checkmate.','Chess Quest game achievement','/badges/game-achievements/pawn-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('pawn-mate','ce550000-0000-4000-8000-000000000037') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000038','Checkmate with King','Game achievement · Checkmates','Creativity','B','50','Move your king (including castling) to reveal checkmate from another piece. Kings never directly check each other.','Chess Quest game achievement','/badges/game-achievements/king-move-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('king-move-mate','ce550000-0000-4000-8000-000000000038') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000039','Smothered Mate','Game achievement · Checkmates','Creativity','B','50','Deliver knight checkmate with the enemy king surrounded on every on-board neighboring square by its own pieces.','Chess Quest game achievement','/badges/game-achievements/smothered-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('smothered-mate','ce550000-0000-4000-8000-000000000039') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000040','Smothered Pork Checkmate','Game achievement · Checkmates','Creativity','A','100','Deliver smothered mate while your knight also attacks a queen or rook and an enemy pawn attacks the knight but cannot legally capture it.','Chess Quest game achievement','/badges/game-achievements/smothered-pork.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('smothered-pork','ce550000-0000-4000-8000-000000000040') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000041','En Passant Checkmate','Game achievement · Checkmates','Creativity','A','100','Deliver checkmate with an en passant capture.','Chess Quest game achievement','/badges/game-achievements/en-passant-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('en-passant-mate','ce550000-0000-4000-8000-000000000041') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000042','g5#','Game achievement · Checkmates','Creativity','A','100','Deliver checkmate with a pawn move to g5.','Chess Quest game achievement','/badges/game-achievements/g5-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('g5-mate','ce550000-0000-4000-8000-000000000042') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000043','Double-Check Checkmate','Game achievement · Checkmates','Creativity','B','50','Deliver checkmate with two pieces checking the king.','Chess Quest game achievement','/badges/game-achievements/double-check-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('double-check-mate','ce550000-0000-4000-8000-000000000043') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000044','Block a Check with Checkmate','Game achievement · Checkmates','Creativity','A','100','Answer a check with a non-king, non-capturing move that blocks the check and delivers checkmate.','Chess Quest game achievement','/badges/game-achievements/block-check-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('block-check-mate','ce550000-0000-4000-8000-000000000044') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000045','O-O#','Game achievement · Checkmates','Creativity','A','100','Deliver checkmate by castling kingside.','Chess Quest game achievement','/badges/game-achievements/castle-kingside-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('castle-kingside-mate','ce550000-0000-4000-8000-000000000045') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000046','O-O-O#','Game achievement · Checkmates','Creativity','A','100','Deliver checkmate by castling queenside.','Chess Quest game achievement','/badges/game-achievements/castle-queenside-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('castle-queenside-mate','ce550000-0000-4000-8000-000000000046') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000047','Promote to Bishop Checkmate','Game achievement · Checkmates','Creativity','A','100','Promote to a bishop with checkmate.','Chess Quest game achievement','/badges/game-achievements/bishop-promotion-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('bishop-promotion-mate','ce550000-0000-4000-8000-000000000047') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000048','Promote to Knight Checkmate','Game achievement · Checkmates','Creativity','A','100','Promote to a knight with checkmate.','Chess Quest game achievement','/badges/game-achievements/knight-promotion-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('knight-promotion-mate','ce550000-0000-4000-8000-000000000048') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000049','Bishop + Knight Checkmate','Game achievement · Checkmates','Creativity','A','100','Checkmate a lone king using only your king, one bishop and one knight.','Chess Quest game achievement','/badges/game-achievements/bishop-knight-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('bishop-knight-mate','ce550000-0000-4000-8000-000000000049') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000050','2-Bishop Checkmate','Game achievement · Checkmates','Creativity','B','50','Deliver mate with only your king and two bishops remaining.','Chess Quest game achievement','/badges/game-achievements/two-bishop-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('two-bishop-mate','ce550000-0000-4000-8000-000000000050') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000051','4-Knight Checkmate','Game achievement · Checkmates','Creativity','A','100','Deliver mate with only your king and four knights remaining.','Chess Quest game achievement','/badges/game-achievements/four-knight-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('four-knight-mate','ce550000-0000-4000-8000-000000000051') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000052','4-Knight Cube Checkmate','Game achievement · Checkmates','Creativity','A','100','Deliver mate with only your king and four knights arranged in a 2-by-2 square.','Chess Quest game achievement','/badges/game-achievements/four-knight-cube-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('four-knight-cube-mate','ce550000-0000-4000-8000-000000000052') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000053','6-Knight Rectangle Checkmate','Game achievement · Checkmates','Creativity','A','100','Deliver mate with only your king and six knights arranged in a rectangle.','Chess Quest game achievement','/badges/game-achievements/six-knight-rectangle-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('six-knight-rectangle-mate','ce550000-0000-4000-8000-000000000053') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000054','Checkmate in 2 Moves','Game achievement · Checkmates','Creativity','B','50','Deliver checkmate on full move 2 from the standard starting position.','Chess Quest game achievement','/badges/game-achievements/mate-move-2.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('mate-move-2','ce550000-0000-4000-8000-000000000054') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000055','Checkmate in 3 Moves','Game achievement · Checkmates','Creativity','B','50','Deliver checkmate on full move 3 from the standard starting position.','Chess Quest game achievement','/badges/game-achievements/mate-move-3.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('mate-move-3','ce550000-0000-4000-8000-000000000055') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000056','Checkmate in 4 Moves','Game achievement · Checkmates','Creativity','B','50','Deliver checkmate on full move 4 from the standard starting position.','Chess Quest game achievement','/badges/game-achievements/mate-move-4.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('mate-move-4','ce550000-0000-4000-8000-000000000056') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000057','Mona Lisa Checkmate','Game achievement · Checkmates','Creativity','A','100','Checkmate with your original back-rank arrangement, no other friendly pieces, and only the enemy king on c2 (c7 for Black).','Chess Quest game achievement','/badges/game-achievements/mona-lisa.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('mona-lisa','ce550000-0000-4000-8000-000000000057') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000058','Castle after Move 40','Game achievement · Surprises','Creativity','B','50','Castle on full move 41 or later.','Chess Quest game achievement','/badges/game-achievements/late-castle.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('late-castle','ce550000-0000-4000-8000-000000000058') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000059','Promote a Pawn within 8 Moves','Game achievement · Surprises','Creativity','A','100','Promote a pawn by the end of full move 8.','Chess Quest game achievement','/badges/game-achievements/early-promotion.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('early-promotion','ce550000-0000-4000-8000-000000000059') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000060','No Captures before Move 30','Game achievement · Surprises','Creativity','B','50','Reach White''s 30th move without a capture on moves 1–29.','Chess Quest game achievement','/badges/game-achievements/peaceful-opening.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('peaceful-opening','ce550000-0000-4000-8000-000000000060') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000061','10+ Consecutive Captures on the Same Square','Game achievement · Surprises','Creativity','A','100','Participate in ten consecutive half-moves that all capture on the same square.','Chess Quest game achievement','/badges/game-achievements/capture-chain.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('capture-chain','ce550000-0000-4000-8000-000000000061') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000062','12 Pawn Move Opening Win','Game achievement · Opening Curiosities','Creativity','A','100','Win after making only pawn moves on your first twelve turns.','Chess Quest game achievement','/badges/game-achievements/pawn-storm.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('pawn-storm','ce550000-0000-4000-8000-000000000062') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000063','Royal Family Fork','Game achievement · Surprises','Creativity','A','100','Give a knight check that also attacks the enemy queen, a rook and at least one more non-pawn piece; the knight cannot be legally captured.','Chess Quest game achievement','/badges/game-achievements/royal-family-fork.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('royal-family-fork','ce550000-0000-4000-8000-000000000063') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000064','Checkmate with 0.1 seconds','Game achievement · Clock Adventures','Creativity','A','100','Checkmate with 0.10 seconds or less left in a game with no increment. Requires recorded move clocks.','Chess Quest game achievement','/badges/game-achievements/tenth-second-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('tenth-second-mate','ce550000-0000-4000-8000-000000000064') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000065','Avoid-the-Flag Checkmate','Game achievement · Clock Adventures','Creativity','A','100','Make your final twenty moves and checkmate after reaching 1.10 seconds or less, with no increment. Requires recorded move clocks.','Chess Quest game achievement','/badges/game-achievements/avoid-flag-mate.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('avoid-flag-mate','ce550000-0000-4000-8000-000000000065') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000066','Adoption','Game achievement · Match Streaks','Creativity','A','100','Win ten consecutive eligible Academy games against the same opponent, with no intervening eligible Academy game against anyone else. Lichess imports do not count for streaks.','Chess Quest game achievement','/badges/game-achievements/adoption.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('adoption','ce550000-0000-4000-8000-000000000066') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000067','Double Adoption','Game achievement · Match Streaks','Creativity','A','100','Win twenty consecutive eligible Academy games against the same opponent, with no intervening eligible Academy game against anyone else. Lichess imports do not count for streaks.','Chess Quest game achievement','/badges/game-achievements/double-adoption.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('double-adoption','ce550000-0000-4000-8000-000000000067') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000068','Clutch Pawn','Game achievement · Clock Adventures','Creativity','A','100','Win on time with only a king and one pawn while at least ten material points behind.','Chess Quest game achievement','/badges/game-achievements/clutch-pawn.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('clutch-pawn','ce550000-0000-4000-8000-000000000068') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000069','Win with Insufficient Material','Game achievement · Clock Adventures','Creativity','B','50','Win on time with only a king and one bishop or knight, where the platform''s rules permit the win because of the opponent''s remaining material.','Chess Quest game achievement','/badges/game-achievements/minor-piece-flag.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('minor-piece-flag','ce550000-0000-4000-8000-000000000069') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000070','Flag Opponent Who Had Mate in 1','Game achievement · Clock Adventures','Creativity','B','50','Win on time when the opponent, whose turn it is, had a legal checkmate in one.','Chess Quest game achievement','/badges/game-achievements/flag-mate-in-one.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('flag-mate-in-one','ce550000-0000-4000-8000-000000000070') on conflict do nothing;
insert into public.badges(id,name,description,category,tier,xp_value,unlock_requirement,visual_theme,art_image_url,generation_status) values('ce550000-0000-4000-8000-000000000071','Lefong','Game achievement · Surprises','Creativity','B','50','Capture a recently developed fianchetto bishop with your bishop by move 10, without an immediate recapture, using the Lefong pattern.','Chess Quest game achievement','/badges/game-achievements/lefong.svg','selected') on conflict(id) do nothing;
insert into public.game_achievement_rules(key,badge_id) values('lefong','ce550000-0000-4000-8000-000000000071') on conflict do nothing;
